version = 1

test_patterns = [
  "\"test/**\",",
  "\"integration_tests/tests_*.ts\",",
  "\"**/*_test.ts\""
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  dialect = "flow"




